version: "3.6"

services:
  db:
    container_name: database1
    build:
      context: .
      dockerfile: Docker-db
    restart: always
    volumes:
      - ./db:/db
    ports:
      - 3307:3306

  # api:
  #   container_name: api1
  #   build: .
  #   restart: always
  #   volumes:
  #     - ./:/api
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - db
  #   links:
  #     - "db:database1"
