on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: smraalm/node:1.0
    steps:
      - uses: actions/challenge@api
      - name: build and push to docker
      uses: docker/build-push-actions@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
