name: deploy
on:
  push:
    branches:
      - api
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:

      # - uses: actions/checkout@v2
      # - name: AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}us-east-1

      # - name: helm deploy
      #   uses: koslib/helm-eks-action@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #   with:
      #     command: helm upgrade <release name> --install --wait <chart> -f <path to values.yaml>
      - uses: actions/checkout@api
      - name: build and push to docker
      uses: docker/build-push-actions@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
